[package]
name = "interactive"
version = "0.1.0"
authors = ["Dmitrii Samsonov <blitzarx1@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
egui_graphs = { path = "../.." }
egui = "0.30"
eframe = "0.30"
petgraph = "0.6"
